### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by coaoac** [tester22/com.Tempiro#1]
Hello! Does the app work at all? Installed 3 smart switches and they do not seem to update nor receive instructions. 
![A3C9780B-B9EC-46B0-9433-08D2685AF6E1](https://user-images.githubusercontent.com/73089/151375155-2c9bbb64-82c8-4b9b-9a6d-1ed9d5648421.png)
![CF767D64-150D-4C90-9F7F-20807F3F3A6E](https://user-images.githubusercontent.com/73089/151375192-f8cfe9c8-ce56-4bbb-94bf-6a15fbe7c40a.png)

**Comment by tester22** [comment]
It works for me.
But the tempiro switches seems to be sensitive to when other zigbee devices
are turned of.
I moved some lightbulbs that we are using an physical switch on to trådfri
and that made it more stable.
Go to this page to check if the zigbee signal path is broken.
https://tools.developer.homey.app/apps


tors 27 jan. 2022 kl. 15:10 skrev Amine Chaouki ***@***.***>:

**Comment by coaoac** [comment]
Thanks for the tips! In my case I had to move Homey very close to the switches for it to work, within 2m. Would be great if the app notified when Homey is not able to reach the switches. No idea if it is feasible or what it would take to implement though :)

**Comment by tester22** [comment]
The plug-in is just using the built in methods from Homey SDK so there is
no real way to get the state of the communication.

You can get an device like this:
https://www.ikea.com/se/sv/p/tradfri-signalfoerstaerkare-10400408/ and
place it close to the Tempiro fuses to make the connection more stable.

tors 27 jan. 2022 kl. 18:49 skrev Amine Chaouki ***@***.***>:
