### ISSUE TITLE
Fuse stops reporting Power for several days

### ISSUE THREAD

**Issue by magpet01** [tester22/com.Tempiro#3]
The fuse stops to report power for long stretches of time.
It recently stopped report power from 13 oktober until 31 oktober.
1 november it started to report again.

**Comment by tester22** [comment]
Did on/off commands work during this period?
Have you added any other Zigbee devices during this period?
Can you send logs from the application in Homey?

**Comment by tester22** [comment]
Did on/off commands work during this period?
Have you added any other Zigbee devices during this period?
Can you send logs from the application in Homey?
