### ISSUE TITLE
Delay on power metering 

### ISSUE THREAD

**Issue by spislucka** [tester22/com.Tempiro#5]
Iv noticed that the power consumption has a 5-10 minuts delay. Is this maybe a hardware problem? 
The unit was not responding, and after reset it has this delay.

**Comment by tester22** [comment]
This app only reacts to the value sent by the device. https://github.com/tester22/com.Tempiro/blob/main/drivers/smart-fuse/device.js#L71

So there is no logic in the code that would delay the update.
