### ISSUE TITLE
No data after migration 

### ISSUE THREAD

**Issue by spislucka** [tester22/com.Tempiro#7]
Hi I'm been running the new homey pro for some time now. Just found that no data has been recorded since then. 
Is this a bug or has it not been addressed?.

**Comment by tester22** [comment]
Nothing I am aware of. Can you send the diagnostics logs in the app.

**Comment by spislucka** [comment]
> 

0cc7cbc6-7dd3-49bc-85d5-b9cccdbb145d

**Comment by spislucka** [comment]
Have you looked into this yet? :)

**Comment by tester22** [comment]
Kom just hem från kortare resa. Kollade loggen och ser tyvärr inget problem som går att lösa i koden.

**Comment by spislucka** [comment]
Jag gjorde en reparation och nu verkar det funka!
